Repository CryptoverseWeb3/CryptoverseWeb3.com, pull requests merged in 2022-10, with the labels that each got.

#6 feat: blog page
  src/App.jsx
  src/components/BlogCard.jsx
  src/components/Blogs.jsx
  src/components/Navbar.jsx
  src/components/index.js
Labels: enhancement, hacktoberfest

#14 #12 [FEATURE] Improve background design of NEWS page
  package-lock.json
  src/App.jsx
Labels: hacktoberfest-accepted, hacktoberfest

#16 feat: transparent card style
  package-lock.json
  package.json
  src/components/Cryptocurrencies/Cryptocurrencies.jsx
  src/components/Cryptocurrencies/CryptocurrenciesElements.jsx
  src/index.css
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest, hacktoberfest-accepted

#29 Making other card transparent as same as crypto cards [Fixes #25]
  index.html
  package-lock.json
  package.json
  src/components/Footer.jsx
  src/index.css
Labels: 🥗 status: ready for merge, ✔ status: review complete, hacktoberfest, hacktoberfest-accepted
